apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - site.yaml
  - allocation.yaml
  - subnet.yaml
  - softgate.yaml
  - server.yaml
  - serverclustertemplate.yaml
  - switch.yaml
  - controller.yaml
  - vnet.yaml
  - vpc.yaml
  - l4lb.yaml
  - bgp.yaml
  - link.yaml
  - nat.yaml
  - inventoryprofile.yaml
