
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.6.1
  creationTimestamp: null
  name: servermeta.k8s.netris.ai
spec:
  group: k8s.netris.ai
  names:
    kind: ServerMeta
    listKind: ServerMetaList
    plural: servermeta
    singular: servermeta
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ServerMeta is the Schema for the servermeta API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ServerMetaSpec defines the desired state of ServerMeta
            properties:
              asn:
                type: integer
              customData:
                type: string
              description:
                type: string
              id:
                type: integer
              imported:
                type: boolean
              mainIp:
                type: string
              mgmtIp:
                type: string
              portsCount:
                type: integer
              profileid:
                type: integer
              reclaimPolicy:
                type: boolean
              serverGeneration:
                format: int64
                type: integer
              serverName:
                type: string
              siteid:
                type: integer
              srvRole:
                type: string
              tags:
                items:
                  type: string
                type: array
              tenantid:
                type: integer
              uuid:
                type: string
            required:
            - id
            - imported
            - reclaimPolicy
            - serverGeneration
            - serverName
            type: object
          status:
            description: ServerMetaStatus defines the observed state of ServerMeta
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []

